service: serverless-plugin-dynamodb-pitr-example-v1

plugins:
  localPath: '../../../'
  modules:
    - serverless-plugin-dynamodb-pitr

provider:
  name: aws
  runtime: nodejs10.x

custom:
  dynamodbPitr:
    ignore:
      - ExcludedTable

resources:
  Resources:
    IncludedTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: IncludedTable
    ExcludedTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ExcludedTable
    WithoutPropertiesTable:
      Type: AWS::DynamoDB::Table
    SQSQueue:
      Type: AWS::SQS::Queue
